version: "2"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
            - ./etc/apache2/sites-available:/etc/apache2/sites-available
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: FINAL_PROJ
            MYSQL_USER: FINAL_PROJ
            MYSQL_PASSWORD: DBPassword@
            MYSQL_ROOT_PASSWORD: R00tP@ssw0rd
            MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: R00tP@ssw0rd
    load:
        image: mysql
        command: ["sh", "-c", "sleep 10s && mysql -h db -u FINAL_PROJ -pDBPassword@ FINAL_PROJ < /data/databaseFinalProject.sql"]
        volumes:
            - ./data:/data
        depends_on:
            - db
volumes:
    persistent: